name: clima
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_svg: ^2.2.1
  geolocator: ^14.0.2
  get: ^4.7.2
  http: ^1.5.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/backgrounds/

flutter_launcher_icons:
  android: true                 # Generar para Android
  ios: true                     # Generar para iOS
  image_path: "assets/lluvia.png" # Ruta a tu imagen
  min_sdk_android: 21           # Requerido para iconos adaptativos
